/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cecar.vista;

import edu.cecar.controladores.ControladorGestionarEmpleado;
import edu.cecar.modelo.Empleado;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 1102833310
 */
public class vistaGestionarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    ControladorGestionarEmpleado controladorGestionarEmpleado = new ControladorGestionarEmpleado();

    public vistaGestionarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_nombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_fecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_direccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_departamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        text_salario = new javax.swing.JTextField();
        boton_guardar = new javax.swing.JButton();
        boton_consultar = new javax.swing.JButton();
        boton_eliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(853, 659));
        getContentPane().setLayout(null);

        text_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_idActionPerformed(evt);
            }
        });
        getContentPane().add(text_id);
        text_id.setBounds(380, 130, 150, 30);

        jLabel1.setText("IDENTIFICACIÓN:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 140, 110, 14);

        jLabel2.setText("NOMBRES COMPLETOS:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 200, 140, 14);
        getContentPane().add(text_nombres);
        text_nombres.setBounds(380, 190, 150, 30);

        jLabel3.setText("FECHA DE NACIMIENTO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 270, 140, 14);
        getContentPane().add(text_fecha);
        text_fecha.setBounds(380, 260, 150, 30);

        jLabel4.setText("DIRECCION DE RESIDENCIA:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 330, 150, 14);
        getContentPane().add(text_direccion);
        text_direccion.setBounds(380, 320, 150, 30);

        jLabel5.setText("DEPARTAMENTO - OFICINA:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 390, 170, 14);

        text_departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_departamentoActionPerformed(evt);
            }
        });
        getContentPane().add(text_departamento);
        text_departamento.setBounds(380, 380, 150, 30);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("SALARIO:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 450, 130, 14);

        text_salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_salarioActionPerformed(evt);
            }
        });
        getContentPane().add(text_salario);
        text_salario.setBounds(380, 440, 150, 30);

        boton_guardar.setText("GUARDAR");
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_guardar);
        boton_guardar.setBounds(280, 510, 110, 40);

        boton_consultar.setText("CONSULTAR");
        getContentPane().add(boton_consultar);
        boton_consultar.setBounds(400, 510, 110, 40);

        boton_eliminar.setText("ELIMINAR");
        boton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_eliminar);
        boton_eliminar.setBounds(520, 510, 110, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("GESTION DE EMPLEADOS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 40, 260, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_idActionPerformed

    private void text_departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_departamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_departamentoActionPerformed

    private void text_salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_salarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_salarioActionPerformed

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
     
        try {
            // TODO add your handling code here:
            controladorGestionarEmpleado.GestionarEmpleado(new Empleado(Integer.parseInt(text_id.getText()),text_nombres.getText(), text_fecha.getText(),text_direccion.getText(),text_departamento.getText(),Integer.parseInt(text_salario.getText())), "guardar");
        } catch (SQLException ex) {
            Logger.getLogger(vistaGestionarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boton_guardarActionPerformed

    private void boton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaGestionarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaGestionarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaGestionarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaGestionarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaGestionarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_consultar;
    private javax.swing.JButton boton_eliminar;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField text_departamento;
    private javax.swing.JTextField text_direccion;
    private javax.swing.JTextField text_fecha;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_nombres;
    private javax.swing.JTextField text_salario;
    // End of variables declaration//GEN-END:variables
}
